language: generic

env:
  global:
  - 'FTP_USER=testtravis_travis.alfutures.co.uk'
  - 'FTP_PASSWORD=travisPassword'
after_success:
  "curl --ftp-create-dirs -T fooindex.html -u $FTP_USER:$FTP_PASSWORD ftp://travis.alfutures.co.uk"
